In [77]:
import pandas as pd

with pd.ExcelFile('Dados_climaticos_historicos.xlsx') as xls:
        df_macae = pd.read_excel(xls, sheet_name='Historico_Clima_Macae', header=3)
        df_rio = pd.read_excel(xls, sheet_name='Historico_Clima_Rio_de_Janeiro', header=3)
        
        # Exibir os primeiros registros dos DataFrames para verificar se foram lidos corretamente
        print("DataFrame de Macaé:")
        print(df_macae.head())
        print("\nDataFrame do Rio de Janeiro:")
        print(df_rio.head())

DataFrame de Macaé:
                     Meses  Janeiro  Fevereiro   Março  Abril  Maio  Junho  \
0   Temperatura média (°C)    25.80      26.00   25.50  24.10  22.0  21.20
1  Temperatura mínima (°C)    23.50      23.60   23.30  21.90  19.6  18.50
2  Temperatura máxima (°C)    29.10      29.50   28.50  27.10  25.0  24.50
3               Chuva (mm)   175.00     105.00  154.00  85.00  60.0  31.00
4               Umidade(%)     0.81       0.81    0.83   0.82   0.8   0.81

   Julho  Agosto  Setembro  Outubro  Novembro  Dezembro
0  20.70   21.00     21.80    22.90     23.50     24.90
1  17.90   18.30     19.20    20.50     21.40     22.70
2  24.20   24.70     25.50    26.40     26.50     28.00
3  32.00   32.00     66.00    98.00    186.00    198.00
4   0.79    0.78      0.77     0.79      0.82      0.83

DataFrame do Rio de Janeiro:
                Unnamed: 0  Janeiro  Fevereiro   Março  Abril   Maio  Junho  \
0   Temperatura média (°C)    26.70      27.00   25.90  24.30  21.80   20.8
1  Temperatura mínima (°C)    23.30      23.30   22.70  21.10  18.20   16.8
2  Temperatura máxima (°C)    31.20      31.70   30.20  28.50  26.20   25.8
3               Chuva (mm)   172.00     117.00  153.00  99.00  81.00   52.0
4               Umidade(%)     0.79       0.78    0.81   0.81   0.81    0.8

   Julho  Agosto  Setembro  Outubro  Novembro  Dezembro
0  20.10   20.90     22.20    23.70      24.2      25.8
1  16.00   16.50     18.10    20.00      21.0      22.4
2  25.40   26.50     27.50    28.60      28.5      30.1
3  55.00   45.00     81.00    98.00     143.0     156.0
4   0.79    0.76      0.75     0.76       0.8       0.8

In [78]:
def calcular_media_anual(dataframe):
    # Selecionar apenas as colunas de temperaturas (mínima, máxima e média) para os meses
    colunas_temperaturas = dataframe.columns[1:13]

    # Calcular a média anual para cada conjunto de registros de temperaturas
    media_anual = dataframe[colunas_temperaturas].mean(axis=1)

    return media_anual

# Calcular a média anual para Macaé
media_anual_macao = calcular_media_anual(df_macao)

# Calcular a média anual para o Rio de Janeiro
media_anual_rio = calcular_media_anual(df_rio)

# Exibir as médias anuais para cada cidade
print("Média Anual para Macaé:")
print(media_anual_macao)

print("\nMédia Anual para o Rio de Janeiro:")
print(media_anual_rio)

Média Anual para Macaé:
0     23.283333
1     20.866667
2     26.583333
3    101.833333
4      0.805000
5      8.916667
6      7.716667
7           NaN
8           NaN
dtype: float64

Média Anual para o Rio de Janeiro:
0     23.616667
1     19.950000
2     28.350000
3    104.333333
4      0.788333
5      9.333333
6      8.000000
7           NaN
8           NaN
dtype: float64

In [79]:
# Função para responder às perguntas
def analises_climaticas(dataframe, cidade):
    # Mês de maior temperatura
    mes_maior_temp = dataframe.iloc[:, 1:13].mean().idxmax()
    
    # Mês de menor temperatura
    mes_menor_temp = dataframe.iloc[:, 1:13].mean().idxmin()
    
    # Encontrar a coluna de chuva de forma mais segura
    colunas_chuva = [col for col in dataframe.columns if 'Chuva' in col]
    
    if colunas_chuva:
        coluna_chuva = colunas_chuva[0]
        # Mês mais chuvoso
        mes_mais_chuvoso = dataframe[coluna_chuva].idxmax()
        
        # Mês menos chuvoso
        mes_menos_chuvoso = dataframe[coluna_chuva].idxmin()
        
        # Acumulado de chuva anual (mm)
        acumulado_chuva_anual = dataframe[coluna_chuva].sum()
    else:
        mes_mais_chuvoso = "N/A"
        mes_menos_chuvoso = "N/A"
        acumulado_chuva_anual = "N/A"
    
    # Encontrar a coluna de umidade de forma mais segura
    colunas_umidade = [col for col in dataframe.columns if 'Umidade' in col]
    
    if colunas_umidade:
        coluna_umidade = colunas_umidade[0]
        # Média anual de umidade
        media_umidade_anual = dataframe[coluna_umidade].mean()
    else:
        media_umidade_anual = "N/A"
    
    print(f"Análises Climáticas para {cidade}:")
    print(f"Mês de Maior Temperatura: {mes_maior_temp}")
    print(f"Mês de Menor Temperatura: {mes_menor_temp}")
    print(f"Mês Mais Chuvoso: {mes_mais_chuvoso}")
    print(f"Mês Menos Chuvoso: {mes_menos_chuvoso}")
    print(f"Acumulado de Chuva Anual (mm): {acumulado_chuva_anual}")
    
    # Verificar se a umidade está disponível
    if media_umidade_anual != "N/A":
        print(f"Média Anual de Umidade: {media_umidade_anual:.2f}%")
    else:
        print("Média Anual de Umidade: N/A")
    
     # Criar um DataFrame com os resultados
    resultado = pd.DataFrame({
        "Cidade": [cidade],
        "Mês de Maior Temperatura": [mes_maior_temp],
        "Mês de Menor Temperatura": [mes_menor_temp],
        "Mês Mais Chuvoso": [mes_mais_chuvoso],
        "Mês Menos Chuvoso": [mes_menos_chuvoso],
        "Acumulado de Chuva Anual (mm)": [acumulado_chuva_anual],
        "Média Anual de Umidade": [media_umidade_anual]
    })
    
    return resultado

# Realizar análises para Macaé
analises_climaticas(df_macao, "Macaé")

# Realizar análises para o Rio de Janeiro
analises_climaticas(df_rio, "Rio de Janeiro")

Análises Climáticas para Macaé:
Mês de Maior Temperatura: Dezembro
Mês de Menor Temperatura: Julho
Mês Mais Chuvoso: N/A
Mês Menos Chuvoso: N/A
Acumulado de Chuva Anual (mm): N/A
Média Anual de Umidade: N/A
Análises Climáticas para Rio de Janeiro:
Mês de Maior Temperatura: Janeiro
Mês de Menor Temperatura: Agosto
Mês Mais Chuvoso: N/A
Mês Menos Chuvoso: N/A
Acumulado de Chuva Anual (mm): N/A
Média Anual de Umidade: N/A

,Cidade,Mês de Maior Temperatura,Mês de Menor Temperatura,Mês Mais Chuvoso,Mês Menos Chuvoso,Acumulado de Chuva Anual (mm),Média Anual de Umidade
0,Rio de Janeiro,Janeiro,Agosto,N/A,N/A,N/A,N/A

In [80]:
# Realizar análises para Macaé
df_resultado_macao = analises_climaticas(df_macao, "Macaé")

# Realizar análises para o Rio de Janeiro
df_resultado_rio = analises_climaticas(df_rio, "Rio de Janeiro")


# Criar um novo arquivo Excel e salvar os resultados em abas separadas
with pd.ExcelWriter('Relatorio_Analises_Climaticas.xlsx') as writer:
    df_resultado_macao.to_excel(writer, sheet_name='Historico_Clima_Macae', index=False)
    df_resultado_rio.to_excel(writer, sheet_name='Historico_Clima_Rio_de_Janeiro', index=False)

Análises Climáticas para Macaé:
Mês de Maior Temperatura: Dezembro
Mês de Menor Temperatura: Julho
Mês Mais Chuvoso: N/A
Mês Menos Chuvoso: N/A
Acumulado de Chuva Anual (mm): N/A
Média Anual de Umidade: N/A
Análises Climáticas para Rio de Janeiro:
Mês de Maior Temperatura: Janeiro
Mês de Menor Temperatura: Agosto
Mês Mais Chuvoso: N/A
Mês Menos Chuvoso: N/A
Acumulado de Chuva Anual (mm): N/A
Média Anual de Umidade: N/A